export const PRODUCT_INFO = [
    {
        productImg: '/image/product/a_120a84f036724d0d97a2343aafff4ecf.svg',
        brandName: 'Jordan',
        productName: 'Jordan 1 High Golf White Black',
        price: '257,000원',
        priceInfo: '즉시 구매가',
    },
    {
        productImg: '/image/product/100-percent.png',
        brandName: 'Stussy',
        productName: 'Stussy Tour T-Shirt Black',
        price: '101,000원',
        priceInfo: '즉시 구매가',
    },
    {
        productImg: '/image/product/a_120a84f036724d0d97a2343aafff4ecf.svg',
        brandName: 'Jordan',
        productName: 'Jordan 1 High Golf White Black',
        price: '257,000원',
        priceInfo: '즉시 구매가',
    },
    {
        productImg: '/image/product/100-percent.png',
        brandName: 'Stussy',
        productName: 'Stussy Tour T-Shirt Black',
        price: '101,000원',
        priceInfo: '즉시 구매가',
    },
    {
        productImg: '/image/product/a_120a84f036724d0d97a2343aafff4ecf.svg',
        brandName: 'Jordan',
        productName: 'Jordan 1 High Golf White Black',
        price: '257,000원',
        priceInfo: '즉시 구매가',
    },
    {
        productImg: '/image/product/100-percent.png',
        brandName: 'Stussy',
        productName: 'Stussy Tour T-Shirt Black',
        price: '101,000원',
        priceInfo: '즉시 구매가',
    },
    {
        productImg: '/image/product/a_120a84f036724d0d97a2343aafff4ecf.svg',
        brandName: 'Jordan',
        productName: 'Jordan 1 High Golf White Black',
        price: '257,000원',
        priceInfo: '즉시 구매가',
    },
    {
        productImg: '/image/product/100-percent.png',
        brandName: 'Stussy',
        productName: 'Stussy Tour T-Shirt Black',
        price: '101,000원',
        priceInfo: '즉시 구매가',
    },
    {
        productImg: '/image/product/a_120a84f036724d0d97a2343aafff4ecf.svg',
        brandName: 'Jordan',
        productName: 'Jordan 1 High Golf White Black',
        price: '257,000원',
        priceInfo: '즉시 구매가',
    },
    {
        productImg: '/image/product/100-percent.png',
        brandName: 'Stussy',
        productName: 'Stussy Tour T-Shirt Black',
        price: '101,000원',
        priceInfo: '즉시 구매가',
    },
    {
        productImg: '/image/product/a_120a84f036724d0d97a2343aafff4ecf.svg',
        brandName: 'Jordan',
        productName: 'Jordan 1 High Golf White Black',
        price: '257,000원',
        priceInfo: '즉시 구매가',
    },
    {
        productImg: '/image/product/100-percent.png',
        brandName: 'Stussy',
        productName: 'Stussy Tour T-Shirt Black',
        price: '101,000원',
        priceInfo: '즉시 구매가',
    },
];
