export default [
    {
        id: 1,
        alt: 'banner1',
        src: '../mainBannerImages/banner01.png',
        current: 1,
        rgb: 'RGB(242, 242, 242)',
    },
    {
        id: 2,
        alt: 'banner2',
        src: '../mainBannerImages/banner02.png',
        current: 2,
        rgb: 'RGB(117, 89, 192)',
    },
    {
        id: 3,
        alt: 'banner3',
        src: '../mainBannerImages/banner03.png',
        current: 3,
        rgb: 'RGB(17, 17, 17)',
    },
    {
        id: 4,
        alt: 'banner4',
        src: '../mainBannerImages/banner04.png',
        current: 4,
        rgb: 'RGB(240, 239, 235)',
    },
    {
        id: 5,
        alt: 'banner5',
        src: '../mainBannerImages/banner05.png',
        current: 5,
        rgb: 'RGB(229, 218, 219)',
    },
    {
        id: 6,
        alt: 'banner6',
        src: '../mainBannerImages/banner06.png',
        current: 6,
        rgb: 'RGB(3, 3, 3)',
    },
    {
        id: 7,
        alt: 'banner7',
        src: '../mainBannerImages/banner07.png',
        current: 7,
        rgb: 'RGB(220, 220, 220)',
    },
    {
        id: 8,
        alt: 'banner8',
        src: '../mainBannerImages/banner08.png',
        current: 8,
        rgb: 'RGB(248, 241, 241)',
    },
    {
        id: 9,
        alt: 'banner9',
        src: '../mainBannerImages/banner09.png',
        current: 9,
        rgb: 'RGB(9, 202, 41)',
    },
];