export default [
    {
        id: 1,
        alt: 'banner1',
        src: '../bannerImages/banner01.png',
        current: 1,
        rgb: 'RGB(236, 241, 243)',
    },
    {
        id: 2,
        alt: 'banner2',
        src: '../bannerImages/banner02.png',
        current: 2,
        rgb: 'RGB(246, 246, 246)',
    },
    {
        id: 3,
        alt: 'banner3',
        src: '../bannerImages/banner03.png',
        current: 3,
        rgb: 'RGB(235, 235, 237)',
    },
    {
        id: 4,
        alt: 'banner4',
        src: '../bannerImages/banner04.png',
        current: 4,
        rgb: 'RGB(236, 245, 233)',
    },
    {
        id: 5,
        alt: 'banner5',
        src: '../bannerImages/banner05.png',
        current: 5,
        rgb: 'RGB(244, 242, 238)',
    },
    {
        id: 6,
        alt: 'banner6',
        src: '../bannerImages/banner06.png',
        current: 6,
        rgb: 'RGB(244, 235, 236)',
    },
    {
        id: 7,
        alt: 'banner7',
        src: '../bannerImages/banner07.png',
        current: 7,
        rgb: 'RGB(72, 65, 51)',
    },
    {
        id: 8,
        alt: 'banner8',
        src: '../bannerImages/banner08.png',
        current: 8,
        rgb: 'RGB(222, 15, 14)',
    },
    {
        id: 9,
        alt: 'banner9',
        src: '../bannerImages/banner09.png',
        current: 9,
        rgb: 'RGB(0, 72, 232)',
    },
    {
        id: 10,
        alt: 'banner10',
        src: '../bannerImages/banner10.png',
        current: 10,
        rgb: 'RGB(0, 0, 0)',
    },
    {
        id: 11,
        alt: 'banner11',
        src: '../bannerImages/banner11.png',
        current: 11,
        rgb: 'RGB(28, 28, 28)',
    },
];